services:
  db:
    image: postgres:16.2
    container_name: ${CONTAINER_PREFIX}-db
    hostname: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 2
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mylocal

  app:
    build: .
    container_name: ${CONTAINER_PREFIX}-app
    hostname: app
    command: ./app
    depends_on:
      - db
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "50051:50051"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - mylocal

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "14268:14268"
      - "16686:16686"

networks:
  mylocal:
    driver: bridge